name: Python PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for syntax errors
        run: python -m compileall .

      - name: Run flake8 (linting)
        run: flake8 .

      - name: Spell check with codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          skip: .git,venv,__pycache__,*.svg
          ignore_words_list: "teh,func,ign"
