"""GUI Layout for changing scoreboard settings in main menu."""

import FreeSimpleGUI as Sg  # ignore

import settings


def create_settings_layout(window_width: int) -> list:
    """Create General User Interface layout for changing settings.

    :param window_width: The width of the screen being used
    "param league: The sports league of the team that the user wants to add
    :return layout: List of elements and how the should be displayed
    """
    # color of background
    color = "lightgray"
    checkbox_color = "white"
    # Common base screen widths
    common_base_widths = [1366, 1920, 1440, 1280]
    # Find the largest base width that doesn't exceed the window width using `max()`
    base_width = max([width for width in common_base_widths if width <= window_width], default=1366)
    scale = window_width / base_width

    max_size = 100
    title_size = min(max_size, max(40, int(50 * scale)))
    checkbox_width = min(max_size, max(10, int(25 * scale)))
    checkbox_height = min(max_size, max(2, int(2 * scale)))
    message_size = min(max_size, max(8, int(14 * scale)))
    button_size = min(max_size, max(20, int(40 * scale)))
    text_input_size = min(max_size, max(4, int(6 * scale)))
    top_label_size = min(max_size, max(14, int(28 * scale)))
    bottom_label_size = min(max_size, max(15, int(32 * scale)))

    checkbox_size = min(max_size, max(10, int(20 * scale)))
    text_size = min(max_size, max(12, int(24 * scale)))

    current_settings = settings.read_settings()

    general_setting_layout = Sg.Frame("",
        [
            # Row containing "Live Data Delay", Input, Live Data Message, and Delay Text
            [
                Sg.Text("Change Functionality of Scoreboard:", font=(settings.FONT, bottom_label_size, "underline"),
                        pad=(0, button_size),
                        background_color=color),
                Sg.Push(background_color=color),
            ],
            [Sg.Push(background_color=color),
                Sg.Column(
                    [
                        [Sg.Text("Display Timer:", font=(settings.FONT, top_label_size), background_color=color),
                         Sg.Spin([str(i) for i in range(1000)], key="DISPLAY_NOT_PLAYING_TIMER", enable_events=True,
                                 size=(text_input_size, 1),
                                 font=("Arial", text_size),
                                 initial_value=str(current_settings.get("DISPLAY_NOT_PLAYING_TIMER", 0))),
                         Sg.Text("seconds", font=(settings.FONT, message_size), pad=(0, 0),
                                 background_color=color),
                         ],
                        [
                            Sg.Push(background_color=color),
                            Sg.Text("How often to Display each team when no team is playing",
                                    key="DISPLAY_NOT_PLAYING_TIMER_MESSAGE",
                                    font=(settings.FONT, message_size, "italic"),
                                    background_color=color),
                            Sg.Push(background_color=color),
                        ],
                    ],
                    background_color=color,
                ),
                Sg.Column(
                    [
                        [Sg.Text("Display Timer (LIVE):", font=(settings.FONT, top_label_size),
                                 background_color=color),
                         Sg.Spin([str(i) for i in range(1000)], key="DISPLAY_PLAYING_TIMER", enable_events=True,
                                 size=(text_input_size, 1),
                                 font=("Arial", text_size),
                                 initial_value=str(current_settings.get("DISPLAY_PLAYING_TIMER", 0))),
                         Sg.Text("seconds", font=(settings.FONT, message_size), pad=(0, 0),
                                 background_color=color),
                         ],
                        [
                            Sg.Push(background_color=color),
                            Sg.Text("How often to Display each team when teams are playing",
                                    key="DISPLAY_PLAYING_TIMER_MESSAGE",
                                    font=(settings.FONT, message_size, "italic"),
                                    background_color=color),
                            Sg.Push(background_color=color),
                        ],
                    ],
                    background_color=color,
                ),
                Sg.Push(background_color=color),
            ],
            [
                Sg.Push(background_color=color),
                     Sg.Column(
                    [
                        [Sg.Text("Live Data Delay:", font=(settings.FONT, top_label_size),
                                 background_color=color),
                         Sg.Spin([str(i) for i in range(1000)], key="LIVE_DATA_DELAY", enable_events=True,
                                 size=(text_input_size, 600),
                                 font=("Arial", text_size),
                                 initial_value=str(current_settings.get("LIVE_DATA_DELAY", 0))),
                         Sg.Text("seconds", font=(settings.FONT, message_size), pad=(0, 0),
                                 background_color=color),
                         ],
                        [
                            Sg.Push(background_color=color),
                            Sg.Text("Delay to display live data", key="LIVE_DATA_DELAY_MESSAGE",
                                    font=(settings.FONT, message_size, "italic"),
                                    background_color=color),
                            Sg.Push(background_color=color),
                        ],
                    ],
                    background_color=color,
                ),
                Sg.Column(
                    [
                        [Sg.Text("Display Time:", font=(settings.FONT, top_label_size), background_color=color),
                         Sg.Spin([str(i) for i in range(1000)], key="HOW_LONG_TO_DISPLAY_TEAM", enable_events=True,
                                 size=(text_input_size, 1),
                                 font=("Arial", text_size),
                                 initial_value=str(current_settings.get("HOW_LONG_TO_DISPLAY_TEAM", 0))),
                         Sg.Text("days", font=(settings.FONT, message_size), pad=(0, 0), background_color=color),
                         ],
                        [
                            Sg.Push(background_color=color),
                            Sg.Text("How long to display team info when finished",
                                    key="HOW_LONG_TO_DISPLAY_TEAM_MESSAGE",
                                    background_color=color,
                                    font=(settings.FONT, message_size, "italic")),
                            Sg.Push(background_color=color),
                        ],
                    ],
                    background_color=color,
                ),
                Sg.Push(background_color=color),
            ],
            [Sg.Text("", font=(settings.FONT, bottom_label_size), background_color=color)],
            [Sg.Column(
                    [
                        [Sg.Checkbox("Re-Download Images when Starting", key="always_get_logos",
                                    font=(settings.FONT, top_label_size),
                                    background_color=color,
                                    checkbox_color=checkbox_color,
                                    default=current_settings.get("always_get_logos", False)),
                        ],
                        [
                            Sg.Text("\tOnly do this only if a team's logo has changed\n",
                                    font=(settings.FONT, message_size),
                                    background_color=color),
                        ],
                    ],
                    justification="left",
                    background_color=color,
                    ),
            ],
            [Sg.Column(
                    [
                        [Sg.Checkbox("Prioritize Playing Team(s)", key="prioritize_playing_team",
                            font=(settings.FONT, top_label_size),
                            background_color=color,
                            checkbox_color=checkbox_color,
                            default=current_settings.get("prioritize_playing_team", False)),
                        ],
                        [
                            Sg.Text("\tWhen enabled, displays only teams with live games.",
                                    font=(settings.FONT, message_size), background_color=color),
                        ],
                        [
                            Sg.Text("\tOther teams will display once all live games are finished.\n",
                                    font=(settings.FONT, message_size), background_color=color),
                        ],
                    ],
                    justification="left",
                    background_color=color,
                    ),
            ],
            [
                Sg.Column(
                    [
                        [Sg.Checkbox("Auto Update",
                            key="auto_update",
                            font=(settings.FONT, top_label_size),
                            background_color=color,
                            checkbox_color=checkbox_color,
                            default=current_settings.get("auto_update", False)),
                        ],
                        [
                            Sg.Text("\tThis will automatically check for updates to always be on the latest version",
                                    font=(settings.FONT, message_size), background_color=color),
                        ],
                        [
                            Sg.Text("\tYou can restore from updates via button on main screen",
                                    font=(settings.FONT, message_size), background_color=color),
                        ],
                    ],
                    justification="left",
                    background_color=color,
                    ),
            ],
        ],
        element_justification="center",
        expand_x=True,
        border_width=0,
        background_color=color,
    )

    general_display_layout = Sg.Frame("",
        [
            [
                Sg.Text("Choose What Gets Displayed:", font=(settings.FONT, bottom_label_size, "underline"),
                        background_color=color,
                        pad=(0, button_size)),
                Sg.Push(background_color=color),
            ],
            [Sg.Column([
                [ Sg.Checkbox("Teams Win-Loss Records", key="display_records",
                            font=(settings.FONT, top_label_size),
                            background_color=color,
                            checkbox_color=checkbox_color,
                            default=current_settings.get("display_records", False)),
                ],
                [Sg.Text("\tDisplays always if enabled",
                        font=(settings.FONT, message_size), background_color=color),
                        ],
                [
                Sg.Checkbox("Game Venue", key="display_venue",
                            font=(settings.FONT, top_label_size),
                            background_color=color,
                            default=current_settings.get("display_venue", False),
                            checkbox_color=checkbox_color),
                ],
                [Sg.Text("\tDisplays only before game starts",
                        font=(settings.FONT, message_size), background_color=color),
                        ],
                [
                Sg.Checkbox("Gambling Odds", key="display_odds",
                            font=(settings.FONT, top_label_size),
                            background_color=color, checkbox_color=checkbox_color,
                            default=current_settings.get("display_odds", False)),                         
                ],
                [Sg.Text("\tDisplays only before game starts",
                        font=(settings.FONT, message_size), background_color=color),
                        ],
                [ Sg.Checkbox("Playoff/Championship Image", key="display_playoff_championship_image",
                            font=(settings.FONT, text_size),
                            background_color=color,
                            checkbox_color=checkbox_color,
                            default=current_settings.get("display_playoff_championship_image", False)),
                    ],
                    [Sg.Text("\tDisplays special image if the game is playoff/championship",
                        font=(settings.FONT, message_size), background_color=color),
                        ],
                ],
                    element_justification="left",
                    background_color=color,
                ),
                Sg.Column([
                    [Sg.Checkbox("Series Info", key="display_series",
                                font=(settings.FONT, top_label_size),
                                background_color=color,
                                checkbox_color=checkbox_color,
                                default=current_settings.get("display_series", False)),
                    ],
                    [Sg.Text("\tDisplays only if applicable and after game ends",
                        font=(settings.FONT, message_size), background_color=color),
                        ],
                    [Sg.Checkbox("Player's Game Stats", key="display_player_stats",
                                font=(settings.FONT, top_label_size),
                                background_color=color,
                                checkbox_color=checkbox_color,
                                default=current_settings.get("display_player_stats", False)),
                    ],
                    [Sg.Text("\tDisplays only after game ends",
                        font=(settings.FONT, message_size), background_color=color),
                        ],
                    [Sg.Checkbox("Date Game Ended", key="display_date_ended",
                            font=(settings.FONT, top_label_size),
                            background_color=color,
                            checkbox_color=checkbox_color,
                            default=current_settings.get("display_date_ended", False)),
                    ],
                    [Sg.Text("\tDisplays only after game ends",
                        font=(settings.FONT, message_size), background_color=color),
                        ],
                    [Sg.Checkbox("Display Broadcast", key="display_network",
                            font=(settings.FONT, top_label_size),
                            background_color=color,
                            checkbox_color=checkbox_color,
                            default=current_settings.get("display_network", False)),
                    ],
                    [Sg.Text("\tDisplays only if applicable",
                        font=(settings.FONT, message_size), background_color=color),
                        ],
                ],
                    element_justification="left",
                    background_color=color,
                ),
            ],
        ],
        element_justification="center",
        expand_x=True,
        border_width=0,
        background_color=color,
    )

    specific_settings_layout = Sg.Frame("",
        [
            [
                Sg.Text("Change What Displays for Specific Sport:",
                        font=(settings.FONT, bottom_label_size, "underline"),
                        background_color=color,
                        pad=(0, button_size)),
             Sg.Push(background_color=color),
             ],
            [Sg.Push(background_color=color),
             Sg.Column([
                 [Sg.Push(background_color=color),
                     Sg.Text("MLB", font=(settings.FONT, bottom_label_size), background_color=color),
                     Sg.Push(background_color=color),
                     ],
                 [Sg.Checkbox("Last Pitch", key="display_last_pitch",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_last_pitch", False))],
                 [Sg.Checkbox("Play Description", key="display_play_description",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_play_description", False))],
                 [Sg.Checkbox("Bases", key="display_bases",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_bases", False))],
                 [Sg.Checkbox("Count", key="display_balls_strikes",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_balls_strikes", False))],
                 [Sg.Checkbox("Hits/Errors", key="display_hits_errors",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_hits_errors", False))],
                 [Sg.Checkbox("Pitcher/Batter", key="display_pitcher_batter",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_pitcher_batter", False))],
                 [Sg.Checkbox("Inning", key="display_inning",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_inning", False))],
                 [Sg.Checkbox("Outs", key="display_outs",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_outs", False))],
             ], vertical_alignment="top", justification="center", background_color=color),
             Sg.Column([
                 [Sg.Push(background_color=color),
                  Sg.Text("NBA", font=(settings.FONT, bottom_label_size), background_color=color),
                  Sg.Push(background_color=color)],
                 [Sg.Checkbox("Timeouts", key="display_nba_timeouts",
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              background_color=color,
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nba_timeouts", False))],
                 [Sg.Checkbox("Bonus", key="display_nba_bonus", size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              background_color=color,
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nba_bonus", False))],
                 [Sg.Checkbox("Game Clock", key="display_nba_clock",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nba_clock", False))],
                 [Sg.Checkbox("Shooting Stats", key="display_nba_shooting",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nba_shooting", False))],
                [Sg.Checkbox("Play-by-Play", key="display_nba_play_by_play",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nba_play_by_play", False))],
             ], vertical_alignment="top", justification="center", background_color=color),
             Sg.Column([
                 [Sg.Push(background_color=color),
                  Sg.Text("NHL", font=(settings.FONT, bottom_label_size), background_color=color),
                  Sg.Push(background_color=color),
                  ],
                 [Sg.Checkbox("Shots On Goal", key="display_nhl_sog",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nhl_sog", False))],
                 [Sg.Checkbox("Power Play", key="display_nhl_power_play",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nhl_power_play", False))],
                 [Sg.Checkbox("Game Clock", key="display_nhl_clock",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nhl_clock", False))],
                 [Sg.Checkbox("Play-by-Play", key="display_nhl_play_by_play",
                              background_color=color,
                               size=(checkbox_width, checkbox_height),
                               font=(settings.FONT, checkbox_size),
                               checkbox_color=checkbox_color,
                               default=current_settings.get("display_nhl_play_by_play", False))],
             ], vertical_alignment="top", justification="center", background_color=color),
             Sg.Column([
                 [Sg.Push(background_color=color),
                  Sg.Text("NFL", font=(settings.FONT, bottom_label_size), background_color=color),
                  Sg.Push(background_color=color),
                  ],
                 [Sg.Checkbox("Timeouts", key="display_nfl_timeouts",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nfl_timeouts", False))],
                 [Sg.Checkbox("RedZone", key="display_nfl_redzone",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nfl_redzone", False))],
                 [Sg.Checkbox("Possession", key="display_nfl_possession",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nfl_possession", False))],
                 [Sg.Checkbox("Down/Yardage", key="display_nfl_down",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nfl_down", False))],
                 [Sg.Checkbox("Game Clock", key="display_nfl_clock",
                              background_color=color,
                              size=(checkbox_width, checkbox_height),
                              font=(settings.FONT, checkbox_size),
                              checkbox_color=checkbox_color,
                              default=current_settings.get("display_nfl_clock", False))],
             ], vertical_alignment="top", justification="center", background_color=color),
             Sg.Push(background_color=color),
             ],
        ],
        border_width=0,
        expand_x=True,
        size=(window_width * 0.9, Sg.Window.get_screen_size()[1] * 0.7),
        background_color=color,
    )

    return [
        [Sg.Push(), Sg.Text("Settings", font=(settings.FONT, title_size, "underline")), Sg.Push()],
        [Sg.VPush()],
        [Sg.Frame("",
            [
                [Sg.Column(
                    [
                        [general_setting_layout],
                        [general_display_layout],
                        [specific_settings_layout],
                    ],
                    scrollable=True,
                    vertical_scroll_only=True,
                    element_justification="center",
                    background_color=color,
                    size=(window_width, int(Sg.Window.get_screen_size()[1] / 2)),
                )],
            ],
            border_width=2,
            relief=Sg.RELIEF_SOLID,
            background_color=color,
        )],
        [Sg.VPush()],
        [
         Sg.Push(),
         Sg.Text("", font=(settings.FONT, button_size), key="confirmation_message", text_color="Green"),
         Sg.Push(),
         ],
         [Sg.VPush()],
        [
         Sg.Push(),
         Sg.Button("Save", font=(settings.FONT, button_size)),
         Sg.Button("Back", font=(settings.FONT, button_size)),
         Sg.Push(),
         ],
         [Sg.VPush()],
    ]
