name: Check

on:
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    name: ✅ Syntax Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check for syntax errors
        run: python -m compileall .

  lint-check:
    name: 🧹 flake8 Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt flake8

      - name: Run flake8
        run: flake8 .

  spell-check:
    name: 🔤 Spell Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          skip: .git,venv,__pycache__,*.svg
          ignore_words_list: "teh,func,ign,nd"

  sonarcloud:
    name: 📊 SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install project dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.projectKey=MFerretti27_Scoreboard
            -Dsonar.organization=mferretti27
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pr-description-check:
    name: 📝 PR Description Required
    runs-on: ubuntu-latest

    steps:
      - name: Check PR description
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
            });

            const body = pr.data.body || "";

            if (body.trim().length < 10) {
              core.setFailed("❌ PR description is required and must be at least 10 characters long.");
            } else {
              console.log("✅ PR description is present.");
            }

  issue-link-check:
    name: 🔗 PR Must Reference an Issue
    runs-on: ubuntu-latest

    steps:
      - name: Check for linked issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const body = pr.body || "";
            if (!body.match(/#[0-9]+/)) {
              core.setFailed("❌ PR must reference a GitHub issue (e.g. #123).");
            } else {
              console.log("✅ PR references an issue.");
            }

  secrets-scan:
    name: 🔐 Gitleaks Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2.3.3

  dependency-audit:
    name: 🛡️ pip-audit for Vulnerabilities
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit -r requirements.txt

      - name: Run pip-audit
        run: pip-audit

  type-check:
    name: 🔎 Type Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install mypy and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
          pip install -r requirements.txt

      - name: Run mypy
        run: mypy .